
dataset_settings:

    # Base directory where datasets will be placed
    datasets_dir: "datasets"
    # list of mapping files, one per species. Will be placed in datasets/mapping/species/
    mappings:
      #### Mapping options:
      # *mapping_file*: path to file. Can be gzipped
      # *species*: the name of the species 
      # *url*: the url of the file to download
      # *file_type*: type of mapping file. Current can be: 
      #     'list': a list of mappings (i.e., many-to-many) where the first column is a uniprot ID, second is the namespace, and third is the ID of the other namespace
      #     'table': a table of 1-to-1 mappings.
      # *namespaces*: namespaces to keep from the file. If 'all' is given, then keep all of the mappings. If *file_type* is table, should be the column names. 
          - mapping_file: "HUMAN_9606_idmapping.dat.gz"
            species: "human"
            url: "ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/idmapping/by_organism/HUMAN_9606_idmapping.dat.gz"
            type: "list"
            #namespaces: ["all"]
            namespaces: ["ensembl", "gene_name", "string", "biogrid", "pharmgkb"]

          - mapping_file: "uniprot-reviewed-status.tab.gz"
            species: "human"
            url: "https://www.uniprot.org/uniprot/?query=*&format=tab&force=true&columns=id,reviewed,genes,organism-id&fil=organism:9606&compress=yes"
            type: "table"
            namespaces: ["Status"]

    # Download and parse *gene_sets*, *networks*, *drug targets*, etc.
    datasets_to_download:
      # TODO 
        #gene_sets:
        #  - name: ""

      #### Network options:
      # *name*: name of this network. Will be used as the directory
      # *file_name*: the name of the file to download
      # *network_collection*: T/F. Specifies if the downloaded file is an archive containing many networks
      # *collection_settings*: settings to apply to each of the individual networks.
      # *weighted*: T/F. If False, a column of all 1s (i.e., unweighted) will be added after the first two columns. 
      #     If True, the first column in *columns_to_keep* should be the weights
      # *unpack_command*: The command to run to unpackage the file/archive. (e.g., unzip, gzip, tar -xvf)
      # *namespace*: the namespace of the nodes in the networks
      # *url*: the url of the file to download
      # *taxon*: the NCBI taxonomy ID of the species to which this network belongs. Currently not used.
      # *species*: the name of the species (i.e., human, mouse). TODO should be used to line up with the mapping
      # *prefer_reviewed*: when mapping, if any of the alternate IDs map to a reviewed UniProt ID, keeping only that one. Otherwise keep all UniProt IDs
      # *gzip_files*: gzip the individual files
      # *remove_filename_spaces*: if there are spaces in the file names, remove them
      # *columns_to_keep*: a list of indexes of columns to keep in the new file. Should be >= 2 (first two columns should be the tail and head of the edge) 
      #     If not specified, all columns will be kept
      # *sep*: the delimiter of columns in the files
        networks:
          - name: "stringv11"
            file_name: "9606-uniprot-links-full-v11.txt.gz"
            network_collection: False
            weighted: True
            #unpack_command: "gunzip"
            namespace: "string"
            url: "https://stringdb-static.org/download/protein.links.full.v11.0/9606.protein.links.full.v11.0.txt.gz"
            taxon: 9606
            species: "human"
            mapping_settings:
              # if there are multiple mappings to UniProt IDs, use only the 'reviewed' one(s) 
              prefer_reviewed: True
            # keep all of the columns
            #columns_to_keep: []
            sep: " "

          - name: "tissuenet-v2/hpa-protein"
            file_name: "hpa-protein.zip"
            network_collection: True
            collection_settings:
              gzip_files: True
              remove_filename_spaces: True
            weighted: False
            unpack_command: "unzip"
            namespace: "ensembl"
            url: "http://netbio.bgu.ac.il/tissuenet2-interactomes/TissueNet2.0/HPA-Protein.zip"
            taxon: 9606
            species: "human"
            mapping_settings:
              #keep_multiple: False
              # if there are multiple mappings to UniProt IDs, use only the 'reviewed' one(s) 
              prefer_reviewed: True
            columns_to_keep: []
            sep: "\t"

          - name: "tissuenet-v2/hpa-rnaseq"
            file_name: "hpa-rnaseq.zip"
            network_collection: True
            collection_settings:
              gzip_files: True
              remove_filename_spaces: True
            weighted: False
            unpack_command: "unzip"
            namespace: "ensembl"
            url: "http://netbio.bgu.ac.il/tissuenet2-interactomes/TissueNet2.0/HPA-RNA-Seq.zip"
            taxon: 9606
            species: "human"
            mapping_settings:
              #keep_multiple: False
              # if there are multiple mappings to UniProt IDs, use only the 'reviewed' one(s) 
              prefer_reviewed: True
            columns_to_keep: []
            sep: "\t"

          - name: "tissuenet-v2/gtex-rnaseq"
            file_name: "gtex-rnaseq.zip"
            network_collection: True
            collection_settings:
              gzip_files: True
              remove_filename_spaces: True
            weighted: False
            unpack_command: "unzip"
            namespace: "ensembl"
            url: "http://netbio.bgu.ac.il/tissuenet2-interactomes/TissueNet2.0/GTEx-RNA-Seq.zip"
            taxon: 9606
            species: "human"
            mapping_settings:
              #keep_multiple: False
              # if there are multiple mappings to UniProt IDs, use only the 'reviewed' one(s) 
              prefer_reviewed: True
            columns_to_keep: []
            sep: "\t"

      #### Gene-drug dataset options:
      # *name*: name of this network. Will be used as the directory name
      # *file_name*: the name of the file to download
      # *unpack_command*: The command to run to unpackage the file/archive. (e.g., unzip, gzip, tar -xvf)
      # *namespace*: the namespace of the nodes in the networks
      # *url*: the url of the file to download
      # *taxon*: the NCBI taxonomy ID of the species to which this network belongs. Currently not used.
      # *species*: the name of the species (i.e., human, mouse). TODO should be used to line up with the mapping
      # *prefer_reviewed*: when mapping, if any of the alternate IDs map to a reviewed UniProt ID, keeping only that one. Otherwise keep all UniProt IDs
      # *gzip_files*: gzip the individual files
      # *remove_filename_spaces*: if there are spaces in the file names, remove them
      # *columns_to_keep*: a list of indexes of columns to keep in the new file. Should be >= 2 (first two columns should be the tail and head of the edge) 
      #     If not specified, all columns will be kept
      # *sep*: the delimiter of columns in the files
        drug-targets:
          - name: "pharmgkb"
            file_name: "relationships.zip"
            network_collection: False
            collection_settings:
              gzip_files: True
              remove_filename_spaces: True
            weighted: False
            unpack_command: "unzip"
            namespace: "ensembl"
            # available at https://www.pharmgkb.org/downloads
            url: "https://s3.pgkb.org/data/relationships.zip"
            taxon: 9606
            species: "human"
            mapping_settings:
              #keep_multiple: False
              # if there are multiple mappings to UniProt IDs, use only the 'reviewed' one(s) 
              prefer_reviewed: True
            columns_to_keep: []
            sep: "\t"

# This section contains settings which will be used to create another config file
# in order to run the FastSinkSource pipeline.
# See https://github.com/jlaw9/FastSinkSource/tree/no-ontology for more info
fastsinksource_pipeline_settings:
    # Base directory where the inputs to the FastSinkSource pipeline will be placed
    input_dir: "fss_inputs"
    exp_name: "2020-03-sarscov2-human-ppi" 
    pos_neg_file: "pos-neg/2020-03-sarscov2-human-ppi/pos.txt"
    # *name*: name of the corresponding downloaded network under "datasets_to_download"
    # *network_collection*: T/F use this flag to run all of the networks in the collection
    # *net_version*: if multiple network comparisons will be run, use this to distinguish between them
    # *net_settings*: will be passed directly to the FSS pipeline. See that repo's config file for more info
    networks_to_run:
      - name: "stringv11"
        file_name: "9606-uniprot-links-full-v11.txt.gz"
        # This flag indicates the downloaded file has all string channels (i.e., "full")
        string_networks: True
        net_version: "stringv11-indv/400"
        net_settings:
            weight_method: 'gmw'
            string_nets: 'all'
            string_cutoff: 400
      - name: "stringv11"
        file_name: "9606-uniprot-links-full-v11.txt.gz"
        string_networks: True
        # also run using only the "combined" channel (last column)
        net_version: "stringv11/400"
        net_settings:
            weight_method: 'gmw'
            string_nets: 'combined_score'
            string_cutoff: 400
      - name: "tissuenet-v2/hpa-protein"
        network_collection: True
      - name: "tissuenet-v2/gtex-rnaseq"
        network_collection: True
      - name: "tissuenet-v2/hpa-rnaseq"
        network_collection: True

    # the outputs will follow this structure:
    # outputs/<net_version>/<exp_name>/<alg_name>/output_files
    output_dir: "outputs/"

    # evaluation settings to use when running the pipeline
    eval_settings: 
      cross_validation_folds: 5
      sample_neg_examples_factor: 1
      #num_reps: 1
      #cv_seed: 1

    # Algorithms to run along with their settings.
    # All combinations of parameters will be run. 
    algs: 
        # local has no parameters
        local:
            should_run: [True]
        localplus:
            should_run: [True]

        genemania:
            should_run: [True]
            alpha: [1.0]
            tol: [1e-05]

        genemaniaplus:
            should_run: [True]
            alpha: [1.0]
            tol: [1e-05]

        fastsinksource:
            should_run: [True]
            alpha: [0.99]
            eps: [0]
            max_iters: [10]

        fastsinksourceplus:
            should_run: [True]
            alpha: [0.99]
            eps: [0]
            max_iters: [10]
            # this option isn't needed if alpha is < 1
            #sinksourceplus_lambda: [0]

        sinksource:
            should_run: [True]
            alpha: [1.0]
            eps: [1e-4]
            max_iters: [1000]

        logistic_regression:
            should_run: [True]
            max_iters: [100]

        svm:
            should_run: [True]
            max_iters: [1000]
