algs:
  deepnf:
    # TODO RWR parameters:
    #alpha: []
    #K: []  # number of steps
    #tol: [1e-04]
    #max_iters: [100]
    # embedding parameters: # just using the default values for now
    # model architecture
    #hidden_dims: [[1000, 500, 1000]]
    hidden_dims: [[2500, 1200, 2500]]
    # Number of epochs to train
    epochs: [80]
    batch_size: [64]
    # factor for denoising the data
    noise_factor: [0.5]
    # linear SVM parameters
    # the norm used in penalization
    penalty: ['l2']
    # inverse of regularization strength parameter
    C: [0.1]
    # a value of 0 for gamma will be a linear kernel
    gamma: [0]
    should_run: [True]

eval_settings:
  num_pred_to_write: -1
  num_reps: 100
  sample_neg_examples_factor: 5
input_settings:
  datasets:
#  - exp_name: 2020-03-sarscov2-human-ppi-ace2
#    plot_exp_name: "STRING-400"
#    net_settings:
#      string_cutoff: 400
#      string_nets: combined_score
#      weight_method: add
#    net_version: networks/stringv11/400
#    pos_neg_file: pos-neg/2020-03-sarscov2-human-ppi-ace2/pos.txt
#    string_net_files:
#    - 9606-uniprot-links-full-v11.txt.gz
  # keep this combination for DeepNF only 
  - exp_name: 2020-03-sarscov2-human-ppi-ace2-all
    plot_exp_name: "STRING-all-400"
    multi_net: True
    net_settings:
      string_cutoff: 400
      string_nets: all
      weight_method: gmw
    # network to use when computing the bins for statistical significance
    stat_sig_net_settings: 
      string_nets: combined_score
    net_version: networks/stringv11/400
    pos_neg_file: pos-neg/2020-03-sarscov2-human-ppi-ace2/pos.txt
    string_net_files:
    - 9606-uniprot-links-full-v11.txt.gz
  input_dir: ann_pred_inputs
output_settings:
  output_dir: outputs/


